Questions = [" What is the Italian word for PIE? \na.Mozarella \nb.Pasty \nc.Patty \nd.Pizza",
             " Water boils at 212 Units at which scale? \na.Fahrenheit \nb.Celsius \nc.Rankine \nd.Kelvin",
             " Which sea creature has three hearts? \na.Dolphin \nb.Octopus \nc.Walrus \nd.Seal",
             " Who was the character famous in our childhood rhymes associated with a lamb? \na.Mary \nb.Jack \nc.Johnny \nd.Mukesh",
             " How many bones does an adult human have? \na.206 \nb.208 \nc.201 \nd.196",
             " How many wonders are there in the world? \na.7 \nb.8 \nc.10 \nd.4",
             " What element does not exist? \na.Xf \nb.Re \nc.Si \nd.Pa",
             " How many states are there in India? \na.24 \nb.29 \nc.30 \nd.31",
             " Who invented the telephone? \na.A.G Bell \nb.John Wick \nc.Thomas Edison \nd.G Marconi",
             " Who is Loki? \na.God of Thunder \nb.God of Dwarves \nc.God of Mischief \nd.God of Gods",
             " Who was the first Indian female astronaut ? \na.Sunita Williams \nb.Kalpana Chawla \nc.None of them \nd.Both of them ",
             " What is the smallest continent? \na.Asia \nb.Antarctic \nc.Africa \nd.Australia",
             " The beaver is the national embelem of which country? \na.Zimbabwe \nb.Iceland \nc.Argentina \nd.Canada",
             " How many players are on the field in baseball? \na.6 \nb.7 \nc.9 \nd.8",
             " Hg stands for? \na.Mercury \nb.Hulgerium \nc.Argenine \nd.Halfnium",
             " Who gifted the Statue of Libery to the US? \na.Brazil \nb.France \nc.Wales \nd.Germany",
             " Which planet is closest to the sun? \na.Mercury \nb.Pluto \nc.Earth \nd.Venus",
             " Grand Central Terminal, Park Avenue, New York is the world's ...? \na.largest railway station \nb.highest railway station \nc.longest railway station \nd.None of the above",
             " G-15 is an economic grouping of? \na.Third World Nations \nb.First World Nations \nc.Second World Nations \nd.Fourth World Nations",
             " Hundred year war was fought between which of the following? \na.France and England \nb.Greek and Persian forces \nc.Civil war in England \nd.None of the above",
             " Which of the following is not associated with the UNO? \na.ASEAN \nb.ILO \nc.WHO \nd.UNESCO",
             " Amnesty International is an organisation associated with which of the following fields? \na.Protection of human rights \nb.Protection of Cruelty to animals \nc.Environment protection \nd.Protection of historic monuments",
             " The headquarters of the UNESCO is located in? \na.Paris \nb.New York \nc.Rome \nd.Geneva",
             " Besides UK, USA, Germany and Japan the G-7 countries includes ...? \na.Canada, France and Italy \nb.Canada, France and Russia \nc.Canada, Italy and Netherlands \nd.France, Netherlands and Russia",
             " Who invented the Ballpoint pen? \na.Biro Brothers \nb.Waterman Brothers \nc.Bicc Brothers \nd.Wright Brothers",
             " What Benjamin Franklin invented? \na.Bifocal spectacles \nb.Radio \nc.Barometer \nd.Hygrometer",
             " Where was the yo-yo invented? \na.Philippines \nb.France \nc.United States \nd.England",
             " Which was the 1st non Test playing country to beat India in an international match? \na.Sri Lanka \nb.Zimbabwe \nc.Canada \nd.Kenya",
             " Where did India play its 1st one day international match? \na.Headingley \nb.Lords \nc.The Oval \nd.Eden Gardens",
             " The Indian football team made its first appearance at Olympics in ...? \na.1948 \nb.1936 \nc.1952 \nd.1956",
             " Who was the first captain of Indian Test team? \na.C K Nayudu \nb.Vijay Hazare \nc.Lala Amarnath \nd.Vijay Merchant",
             " How many gold medals have been won by India in the Olympics so far? \na.9 \nb.8 \nc.10 \nd.6",
             " The trident-shaped symbol of Buddhism does not represent ...? \na.Nirvana \nb.Sangha \nc.Buddha \nd.Dhamma",
             " Todar Mal was associated with ...? \na.Finance \nb.Law \nc.Music \nd.Literature",
             " Tipu sultan was the ruler of? \na.Mysore \nb.Hyderabad \nc.Madurai \nd.Vijayanagar",
             " Chlorophyll is a naturally occurring chelate compound in which central metal is? \na.Magnesium \nb.Copper \nc.Iron \nd.Calcium",
             " Quartz crystals normally used in quartz clocks is chemically? \na.silicon dioxide \nb.germanium oxide \nc.a mixture of germanium oxide and silicon dioxide \nd.sodium silicate",
             " Non stick cooking utensils are coated with? \na.Teflon \nb.Polystyrene \nc.PVC \nd.Black Paint",
             " The great Victoria Desert is located in? \na.Australia \nb.Canada \nc.United States \nd.South Africa",
             ' How many months do we have in a year?\na) 12 months\nb) 8 months\nc) 4 months\nd) 36 months',
             ' How many days do we have in a week?\na) 7 days\nb) 8 days\nc) 9 days\nd) 1 day',
             ' How many days are there in a non leap year?\na) 365 days \nb) 366 days \nc) 400 days\nd) 500 days',
             ' What is 2+2 ? \na)3 \nb)4 \nc)5 \nd)6 ',
             ' Which number comes after 6?\na) 2\nb)4 \nc)6 \nd)7 ',
             ' How many colors are there in a rainbow?\na) 3\nb) 5\nc) 6\nd) 7',
             ' Which day comes after Friday?\na) Monday\nb) Saturday\nc) Sunday\nd) None of the above.',
             ' We use our eyes to -\na) see\nb) hear \nc) eat\nd) feel',
             ' We use our ears to -\na) see\nb) hear \nc) eat\nd) feel',
             ' What is a baby frog called?\na) Tadpole\nb) Cow\nc) goat\nd) Tadrod',
             ' Which animal is known as the ‘Ship of the Desert?’\na)Camel \nb) Cow\nc) goat\nd) Tadrod',
             ' How many letters are there in the English alphabet?\na) 32\nb) 26\nc) 54\nd) 21',
             ' What do you call the person who brings a letter to your home from post office?\na) Sales Person\nb) Pilot\nc) Postman\nd) Locopilot',
             ' How do you relate to your maternal grandfather?\na) Mother’s father\nb) Brother\nc) Sister\nd) Paternal Grandfather',
             ' We use our nose to -\na) see\nb) hear \nc) smell\nd) feel',
             ' We use our skin to -\na) see\nb) hear \nc) eat\nd) feel',
             ' Baby of a dog is called\na) Puppy\nb) goat\nc) dog\nd) frog',
             ' Which is the largest animal in the world ?\na) Blue Whale\nb) Humming Bird\nc) African elephant\nd) Whale shark',
             ' Which is the largest animal on land ?\na) Blue Whale\nb) Humming Bird\nc) African elephant\nd) Whale shark']

Answers = ['d', 'a', 'b', 'a', 'a', 'a', 'a', 'b',
           'a', 'c', 'b', 'd', 'd', 'c', 'a', 'b', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'b', 'd', 'd', 'b', 'a', 'b', 'a', 'a', 'b', 'c', 'a', 'c', 'd', 'a', 'a', 'c']
